name: trapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.0+47

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_swiper_null_safety: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.3
  http_interceptor: ^1.0.1
  shared_preferences: ^2.0.6
  fluttertoast: ^8.0.7
  image_picker: ^0.8.2
  permission_handler: 8.1.4+2
  notification_permissions: ^0.6.1
  geolocator: 7.4.0
  qr_flutter: ^4.0.0
  share: ^2.0.4
  image_gallery_saver: ^1.6.9
  path_provider: ^2.0.2
  shimmer: ^2.0.0
  pull_to_refresh: ^2.0.0
  date_time_format: ^2.0.1
  map_launcher: ^2.1.1
  time_picker_widget: ^1.0.0+10
  google_maps_flutter: ^2.0.6
  currency_text_input_formatter: ^2.1.0
  random_string: ^2.3.1
  url_launcher: ^6.0.9
  intl_phone_number_input: ^0.7.0+2
  telephony: ^0.1.4
  keyboard_utils: ^1.3.0
  carousel_slider: ^4.0.0
  encrypt: ^5.0.0
  video_player: ^2.1.12
  razorpay_flutter: ^1.2.7
  crypto: ^3.0.1
  flutter_barcode_scanner: ^2.0.0
  native_pdf_view: ^4.1.0
  flutter_slidable: ^0.6.0
  webview_flutter: ^2.0.10
  scratcher: ^2.1.0
  json_diff: ^0.2.0
  facebook_app_events: ^0.12.0
  freshchat_sdk: ^0.8.0
  easy_localization: ^3.0.0
  pin_code_fields: ^7.3.0
  fl_chart: ^0.36.3
  multiple_stream_builder: ^2.0.0
  flutter_svg: ^0.22.0
  in_app_update: ^2.0.0
  package_info_plus: ^1.0.4
  device_info_plus: ^3.1.0
  flutter_phoenix: ^1.0.0
  printing: ^5.5.0
  flutter_custom_tabs: ^1.0.2
  easy_dynamic_theme: ^2.2.0
  file_picker: ^4.0.0
  youtube_player_iframe: ^2.2.2
  extended_image: ^5.1.2
  battery_plus: ^2.0.1
  connectivity_plus: ^2.0.2
  syncfusion_flutter_datepicker: ^19.3.47

  
  ### Flutter local notification
  flutter_local_notifications: 
  rxdart: ^0.27.1
  ################################################

  ### Firebase
  firebase_core: 1.7.0 
  firebase_messaging: 10.0.8
  cloud_firestore: 2.5.3
  firebase_auth: 3.1.3
  firebase_analytics: 8.3.3
  firebase_dynamic_links: 2.0.10
  firebase_crashlytics: 2.2.3
  firebase_storage: 10.0.5

  flutter_spinkit: ^5.1.0

  uuid: 3.0.5
  
  # State management
  provider: ^5.0.0
  equatable: ^2.0.3

  # responsive_ui
  flutter_screenutil: ^5.0.0+2

  google_map_location_picker:
    path: ./lib/CustomPackages/google_map_location_picker
  
  sms_autofill: ^2.2.0
  upi_pay: ^1.0.1
  json_annotation: ^4.3.0
  freezed_annotation: ^1.0.0
  flutter_logs: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  build_runner: ^2.1.5
  json_serializable: ^6.0.0
  freezed: ^1.0.2+1

flutter_icons:
  android: true
  ios: true
  image_path_android: "img/app_icon_android.png"
  image_path_ios: "img/app_icon_ios.png"
  # flutter pub run flutter_launcher_icons:main 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/
    - img/order/
    - img/top-carousel/
    - img/bottom-carousel/
    - img/home/
    - img/intro/
    - img/help/
    - img/category-icon/
    - img/category-image/
    - img/store-icon/
    - img/refer/
    - img/flags/
    - img/payment_methods/
    - img/lucky_draw/
    - img/coupons/
    - img/promocodes/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  
  # example:
  fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Thin.ttf
        weight: 100
      - asset: fonts/Montserrat-ExtraLight.ttf
        weight: 200
      - asset: fonts/Montserrat-Light.ttf
        weight: 300
      - asset: fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: fonts/Montserrat-ExtraBold.ttf
        weight: 800
      - asset: fonts/Montserrat-Black.ttf
        weight: 900
  #\
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
